# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.boot_timeout = 600

  VAGRANTFILE_DIR = File.dirname(__FILE__)
  REPO_ROOT       = File.expand_path("../..", VAGRANTFILE_DIR)
  INFRA_GITOPS    = File.expand_path("../../../infra-gitops", VAGRANTFILE_DIR)
  WORKDIR = "/home/vagrant/talos-vsphere-lab"
  
  SELECTED_PROVIDER = ENV.fetch('LAB_PROVIDER', 'vmware_desktop')
  DEFAULT_CPUS = 2
  DEFAULT_RAM_MB = 2048
  
  # Lab guest definitions
  nodes = [
    { name: "haproxy-01", box: "bento/ubuntu-24.04", ip: "172.17.20.181" },
    { name: "haproxy-02", box: "bento/oraclelinux-9", ip: "172.17.20.182" }
  ]

  # =========================
  # Function to configure provider with IP
  # =========================
  configure_provider = lambda do |vm, ip_addr|

    case SELECTED_PROVIDER

    when "virtualbox"
      vm.vm.provider "virtualbox" do |vb|
        vb.cpus   = DEFAULT_CPUS
        vb.memory = DEFAULT_RAM_MB
      end

      vm.vm.network "private_network",
                    ip: ip_addr,
                    netmask: "255.255.255.0"

    when "vmware_desktop"
      vm.vm.provider "vmware_desktop" do |v|
        v.vmx["numvcpus"] = DEFAULT_CPUS.to_s
        v.vmx["memsize"]  = DEFAULT_RAM_MB.to_s
      end

      vm.vm.network "private_network",
                    ip: ip_addr,
                    netmask: "255.255.255.0",
                    vmware__adapter_type: "vmxnet3"

    else
      raise "Unsupported LAB_PROVIDER='#{SELECTED_PROVIDER}'. Use 'vmware_desktop' or 'virtualbox'."
    end
  end

  # Create the HAProxy guests
  nodes.each do |node|
    host_name = node[:name]
    ip_addr   = node[:ip]
    fqdn      = "#{host_name}.infra.local"

    config.vm.define host_name do |guest|
      guest.vm.box = node[:box]
      guest.vm.hostname = fqdn
      configure_provider.call(guest, ip_addr)
    end
  end

  config.vm.define "talos-controller" do |controller|
    
    ip_addr = "172.17.20.179"
    controller.vm.box = "bento/oraclelinux-9"
    controller.vm.hostname = "bootstrap.infra.local"
    controller.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh"
    controller.vm.synced_folder REPO_ROOT, WORKDIR
    controller.vm.synced_folder INFRA_GITOPS,
                           "/home/vagrant/infra-gitops",
                           group: "vagrant", owner: "vagrant"    
    configure_provider.call(controller, ip_addr)

    controller.vm.provision "shell",
                            path: "scripts/controller/install-ansible.sh",
                            privileged: false,
                            env: {
                              "ANSIBLE_USER" => "vagrant",
                              "ANSIBLE_PROJECT_PATH" => "#{WORKDIR}/overlays/base/ansible/haproxy"
                            }
    controller.vm.provision "shell",
                            path: "scripts/controller/install-collections.sh",
                            privileged: false,
                            env: {
                              "ANSIBLE_USER" => "vagrant",
                              "ANSIBLE_PROJECT_PATH" => "#{WORKDIR}/overlays/base/ansible/haproxy"
                            }
    

  # config.vm.synced_folder ".", "/home/vagrant/bootstrap", owner: "vagrant", group: "vagrant"

  # config.vm.network "private_network", ip: "192.168.0.90",
  #     :extra_options => {
  #         "dns_nameservers" => ["192.168.0.139", "8.8.4.4"]
  #     }

  # config.vm.provision "shell", inline: <<-SHELL
  #   echo "nameserver 192.168.0.139" | sudo tee /etc/resolv.conf > /dev/null
  #   echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
  #   echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
  #   SHELL
  end

end
