# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.boot_timeout = 600

  VAGRANTFILE_DIR = File.dirname(__FILE__)
  REPO_ROOT       = File.expand_path("../..", VAGRANTFILE_DIR)
  INFRA_GITOPS    = File.expand_path("../../../infra-gitops", VAGRANTFILE_DIR)
  TALOS_VSPHERE_GITOPS = File.expand_path("../../../talos-vsphere-gitops", VAGRANTFILE_DIR)
  TALOS_TOOLCHAIN = File.expand_path("../../../talos-toolchain", VAGRANTFILE_DIR)
  WORKDIR = "/home/vagrant/talos-vsphere-lab"
  CONTROLLER_ANSIBLE_USER = "vagrant"
  CONTROLLER_ANSIBLE_HOME = "/home/#{CONTROLLER_ANSIBLE_USER}"
  CONTROLLER_VENV_PATH = "#{CONTROLLER_ANSIBLE_HOME}/venv"
  CONTROLLER_ANSIBLE_TOOLING_PATH = "#{WORKDIR}/overlays/base/ansible"
  CONTROLLER_ANSIBLE_WORKSPACE_PATH = "#{CONTROLLER_ANSIBLE_TOOLING_PATH}/haproxy"
  CONTROLLER_ANSIBLE_CONFIG_FILE = "#{CONTROLLER_ANSIBLE_TOOLING_PATH}/ansible.cfg"
  CONTROLLER_ANSIBLE_INVENTORY_FILE = "#{CONTROLLER_ANSIBLE_WORKSPACE_PATH}/inventory"
  CONTROLLER_ANSIBLE_PLAYBOOK_FILE = "#{CONTROLLER_ANSIBLE_WORKSPACE_PATH}/playbooks/provision_haproxy.yml"
  
  SELECTED_PROVIDER = ENV.fetch('LAB_PROVIDER', 'vmware_desktop')
  LAB_PORT_AUTOCORRECT = ENV.fetch('LAB_PORT_AUTOCORRECT', 'false') == 'true'
  CONTROLLER_SSH_HOST_PORT = ENV.fetch('LAB_CONTROLLER_SSH_PORT', '22230')
  DEFAULT_CPUS = 2
  DEFAULT_RAM_MB = 2048
  
  # Lab guest definitions
  nodes = [
    { name: "haproxy-01", box: "bento/ubuntu-24.04", ip: "172.17.20.181" },
    { name: "haproxy-02", box: "bento/oraclelinux-9", ip: "172.17.20.182" }
  ]

  # =========================
  # Function to configure provider with IP
  # =========================
  configure_provider = lambda do |vm, ip_addr|

    case SELECTED_PROVIDER

    when "virtualbox"
      vm.vm.provider "virtualbox" do |vb|
        vb.cpus   = DEFAULT_CPUS
        vb.memory = DEFAULT_RAM_MB
      end

      vm.vm.network "private_network",
                    ip: ip_addr,
                    netmask: "255.255.255.0"

    when "vmware_desktop"
      vm.vm.provider "vmware_desktop" do |v|
        v.vmx["numvcpus"] = DEFAULT_CPUS.to_s
        v.vmx["memsize"]  = DEFAULT_RAM_MB.to_s
      end

      vm.vm.network "private_network",
                    ip: ip_addr,
                    netmask: "255.255.255.0",
                    vmware__adapter_type: "vmxnet3"

    else
      raise "Unsupported LAB_PROVIDER='#{SELECTED_PROVIDER}'. Use 'vmware_desktop' or 'virtualbox'."
    end
  end

  # Create the HAProxy guests
  nodes.each do |node|
    host_name = node[:name]
    ip_addr   = node[:ip]
    fqdn      = "#{host_name}.infra.local"

    config.vm.define host_name, autostart: false do |guest|
      guest.vm.box = node[:box]
      guest.vm.hostname = fqdn
      configure_provider.call(guest, ip_addr)
    end
  end

  config.vm.define "talos-controller", autostart: true do |controller|

    ip_addr = "172.17.20.179"
    controller.vm.box = "bento/oraclelinux-9"
    controller.vm.hostname = "bootstrap.infra.local"
    controller.vm.network :forwarded_port, guest: 22, host: CONTROLLER_SSH_HOST_PORT.to_i, id: "ssh",
      host_ip: "127.0.0.1", auto_correct: LAB_PORT_AUTOCORRECT
    controller.vm.synced_folder REPO_ROOT, WORKDIR
    controller.vm.synced_folder INFRA_GITOPS,
                           "/home/vagrant/infra-gitops",
                           group: "vagrant", owner: "vagrant"    
    controller.vm.synced_folder TALOS_VSPHERE_GITOPS,
                           "/home/vagrant/talos-vsphere-gitops",
                           group: "vagrant", owner: "vagrant"
    if File.directory?(TALOS_TOOLCHAIN)
      controller.vm.synced_folder TALOS_TOOLCHAIN,
                             "/home/vagrant/talos-toolchain",
                             group: "vagrant", owner: "vagrant"
    end
    configure_provider.call(controller, ip_addr)

    controller_env = {
      "ANSIBLE_USER" => CONTROLLER_ANSIBLE_USER,
      "ANSIBLE_HOME" => CONTROLLER_ANSIBLE_HOME,
      "VENV_PATH" => CONTROLLER_VENV_PATH,
      "ANSIBLE_TOOLING_PATH" => CONTROLLER_ANSIBLE_TOOLING_PATH,
      "ANSIBLE_WORKSPACE_PATH" => CONTROLLER_ANSIBLE_WORKSPACE_PATH,
      "ANSIBLE_CONFIG_FILE" => CONTROLLER_ANSIBLE_CONFIG_FILE,
      "ANSIBLE_INVENTORY_FILE" => CONTROLLER_ANSIBLE_INVENTORY_FILE,
      "ANSIBLE_PLAYBOOK_FILE" => CONTROLLER_ANSIBLE_PLAYBOOK_FILE
    }

    controller.vm.provision "shell",
                            privileged: false,
                            inline: "bash #{WORKDIR}/overlays/lab/controller/scripts/install-ansible.sh",
                            env: controller_env
    controller.vm.provision "shell",
                            privileged: false,
                            inline: "bash #{WORKDIR}/overlays/lab/controller/scripts/install-collections.sh",
                            env: controller_env
  end

end
