Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-24.04"
  config.ssh.forward_agent = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.boot_timeout = 600

  ESXI_IP = "192.168.0.233"
  ESXI_USER = "root"
  ESXI_PASSWORD = "Senha@123"
  ESXI_DATASTORE = "DATASTORE_02"
  ESXI_NETWORK = "VM Network"
  ESXI_FOLDER = "Vm"

  # export GOVC_URL=https://192.168.0.233
  # export GOVC_USERNAME="root"
  # export GOVC_PASSWORD="Senha@123"
  # export GOVC_INSECURE=true
  # export GOVC_DATASTORE="DATASTORE_02"
  # export GOVC_NETWORK="VM Network"
  # export GOVC_FOLDER="Vm"
  
  ESXI_FOLDER = "Vm"
  # ESXI_DATACENTER = "ha-datacentter"

  config.vm.hostname = "talos-bootstrap.infra.local"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "1"
  end

  # config.vm.synced_folder ".", "/home/vagrant/bootstrap", owner: "vagrant", group: "vagrant"

  # config.vm.network "private_network", ip: "192.168.0.90",
  #     :extra_options => {
  #         "dns_nameservers" => ["192.168.0.139", "8.8.4.4"]
  #     }

  # config.vm.provision "shell", inline: <<-SHELL
  #   echo "nameserver 192.168.0.139" | sudo tee /etc/resolv.conf > /dev/null
  #   echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
  #   echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf > /dev/null
  #   SHELL

  # pass environment variables to the VM
  config.vm.provision "set-env", type: "shell" do |s|
    s.inline = <<-SHELL
      export GOVC_URL=https://${ESXI_IP} \
      export GOVC_USERNAME=${ESXI_USER} \
      export GOVC_PASSWORD=${ESXI_PASSWORD} \
      export GOVC_INSECURE=true \
      export GOVC_DATACENTER=${ESXI_DATACENTER} \
      export GOVC_DATASTORE=${ESXI_DATASTORE} \
      export GOVC_NETWORK=${ESXI_NETWORK} \
      export GOVC_FOLDER=${ESXI_FOLDER}
      SHELL
  end
      
    # Provisioning script
config.vm.provision "setup-guest", type: "shell", path: "scripts/controller/0-install-tools.sh"
#config.vm.provision "bootstrap-talos", type: "shell", path: "scripts/bootstrap.sh", run: "once"

end

