---
haproxy_install_latest: true
haproxy_stats_enabled: true
haproxy_stats_port: 9000
haproxy_stats_user: admin
haproxy_stats_pass: changeme

haproxy_frontends: []
haproxy_backends: []

haproxy_mode: tcp
haproxy_name: haproxy
haproxy_config_template: haproxy.cfg.j2
haproxy_conf_dir: /etc/haproxy
haproxy_conf_file_path: "{{ haproxy_conf_dir }}/{{ haproxy_name }}.cfg"
haproxy_executable_path: /usr/sbin/haproxy
haproxy_ppa_version: ppa:vbernat/haproxy-3.2
haproxy_user: haproxy
haproxy_group: haproxy

haproxy_dependencies:
  - software-properties-common
  - python3-cryptography
  - python3-openssl
  - socat

haproxy_global_maxconn: 4096
haproxy_balance_algorithm: roundrobin
