machine:
  network:
    hostname: talos-cp-lab
    interfaces:
      - interface: eth0 # Verify that this is your interface name (e.g., enp0s1, eth0)
        addresses:
          - 192.168.0.138/24 # Desired static IP in CIDR format
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.0.2 # Your gateway IP
        dhcp: false # Disables DHCP client
#        vip:
#           ip: 192.168.0.100
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  features:
    hostDNS:
      enabled: false
      forwardKubeDNSToHost: false
    # interfaces:
    #   - interface: eth0
        # dhcp: true
        # vip:
        #   ip: 192.168.0.100
      
# cluster:
#   network:
#     cni:
#       name: none
#   proxy:
#     disabled: true
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s-cp-1
auto: off
