#!/usr/bin/env bash
# @describe Install Helm 3 on the lab controller (idempotent).
# @arg --version optional Helm version tag (e.g. v3.19.0). Default: latest v3 release.
# @arg --install-dir optional install directory. Default: /home/vagrant/.local/bin.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
BASE_FUNCTIONS="${REPO_ROOT}/overlays/base/scripts/functions.sh"

# shellcheck source=/dev/null
source "${BASE_FUNCTIONS}"

HELM_VERSION="stable"
INSTALL_DIR="${HOME}/.local/bin"
SHELL_INIT_DIR="${HOME}/.bashrc.d"
HELM_SHELL_FILE="${SHELL_INIT_DIR}/helm-completion.sh"
BASHRC_FILE="${HOME}/.bashrc"

usage() {
  cat <<EOF_USAGE
Usage: $(basename "$0") [options]

Options:
  --version=<tag>      helm version (e.g. v3.19.0) or stable (default)
  --install-dir=<dir>  installation directory (default: ~/.local/bin)
  -h, --help           show this help
EOF_USAGE
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --version=*) HELM_VERSION="${1#*=}"; shift ;;
      --install-dir=*) INSTALL_DIR="${1#*=}"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) usage; die "Unknown argument: $1" ;;
    esac
  done
}

resolve_version() {
  local version_input="$1"
  local resolved="${version_input}"

  if [[ "${version_input}" == "stable" ]]; then
    resolved="$(curl -fsSL "https://api.github.com/repos/helm/helm/releases?per_page=100" | grep -Eo '"tag_name":[[:space:]]*"v3\.[0-9]+\.[0-9]+"' | head -n1 | sed -E 's/.*"v([^"]+)".*/v\1/')"
  fi

  [[ "${resolved}" =~ ^v3\.[0-9]+\.[0-9]+$ ]] || die "Invalid Helm 3 version: ${resolved}. Use a v3.x.y tag."
  printf '%s\n' "${resolved}"
}

current_version() {
  if ! command -v helm >/dev/null 2>&1; then
    return 1
  fi

  local version
  version="$(helm version --short 2>/dev/null | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+' | head -n1 || true)"
  [[ -n "${version}" ]] || return 1
  printf '%s\n' "${version}"
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'amd64\n' ;;
    aarch64|arm64) printf 'arm64\n' ;;
    *) die "Unsupported architecture for Helm install: $(uname -m)" ;;
  esac
}

ensure_path_hint() {
  case ":${PATH}:" in
    *":${INSTALL_DIR}:"*) return 0 ;;
    *)
      log_warn "${INSTALL_DIR} is not in PATH for this shell."
      log_warn "Run: export PATH=\"${INSTALL_DIR}:\$PATH\""
      ;;
  esac
}

ensure_bashrc_sources_init_dir() {
  local marker_begin="# >>> controller bashrc.d >>>"

  touch "${BASHRC_FILE}"
  if grep -Eq 'bashrc\.d' "${BASHRC_FILE}"; then
    return 0
  fi
  if grep -Fq "${marker_begin}" "${BASHRC_FILE}"; then
    return 0
  fi

  cat >>"${BASHRC_FILE}" <<'EOF_BASHRC'
# >>> controller bashrc.d >>>
if [[ -d "${HOME}/.bashrc.d" ]]; then
  for _controller_rc in "${HOME}"/.bashrc.d/*.sh; do
    [[ -f "${_controller_rc}" ]] || continue
    # shellcheck disable=SC1090
    source "${_controller_rc}"
  done
  unset _controller_rc
fi
# <<< controller bashrc.d <<<
EOF_BASHRC
}

configure_helm_shell_integration() {
  mkdir -p "${SHELL_INIT_DIR}"
  cat >"${HELM_SHELL_FILE}" <<'EOF_HELM_RC'
# helm completion (generated by install-helm.sh)
if command -v helm >/dev/null 2>&1; then
  source <(helm completion bash)
fi
EOF_HELM_RC
  chmod 0644 "${HELM_SHELL_FILE}"
  ensure_bashrc_sources_init_dir
}

install_helm() {
  local version="$1"
  local arch="$2"
  local os="linux"
  local tmp_dir tarball url

  tmp_dir="$(mktemp -d)"
  tarball="${tmp_dir}/helm-${version}-${os}-${arch}.tar.gz"
  url="https://get.helm.sh/helm-${version}-${os}-${arch}.tar.gz"

  mkdir -p "${INSTALL_DIR}"
  curl -fsSL -o "${tarball}" "${url}"
  tar -xzf "${tarball}" -C "${tmp_dir}"
  install -m 0755 "${tmp_dir}/${os}-${arch}/helm" "${INSTALL_DIR}/helm"
  rm -rf "${tmp_dir}"
}

main() {
  parse_args "$@"

  local target_version current arch final_version

  target_version="$(resolve_version "${HELM_VERSION}")"
  current="$(current_version || true)"

  if [[ -n "${current}" && "${current}" == "${target_version}" ]]; then
    log_info "helm ${current} already installed. Nothing to do."
    configure_helm_shell_integration
    ensure_path_hint
    return 0
  fi

  arch="$(detect_arch)"

  if [[ -n "${current}" ]]; then
    log_warn "helm ${current} found; upgrading/downgrading to ${target_version}."
  else
    log_info "Installing helm ${target_version}."
  fi

  install_helm "${target_version}" "${arch}"

  final_version="$(current_version || true)"
  [[ "${final_version}" == "${target_version}" ]] || die "Helm install failed. Expected ${target_version}, got ${final_version:-unknown}."

  log_info "helm installed successfully: ${final_version}"
  configure_helm_shell_integration
  ensure_path_hint
  log_info "helm autocompletion configured for new shells."
}

main "$@"
