#!/usr/bin/env bash
# @describe Install talosctl on the lab controller and configure shell completion.
# @arg --version optional talosctl version tag (e.g. v1.12.4).
# @arg --install-dir optional install directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
BASE_FUNCTIONS="${REPO_ROOT}/overlays/base/scripts/functions.sh"

# shellcheck source=/dev/null
source "${BASE_FUNCTIONS}"

TALOSCTL_VERSION=""
INSTALL_DIR=""
SHELL_INIT_DIR="${HOME}/.bashrc.d"
TALOSCTL_SHELL_FILE="${SHELL_INIT_DIR}/talosctl-completion.sh"
BASHRC_FILE="${HOME}/.bashrc"

usage() {
  cat <<EOF_USAGE
Usage: $(basename "$0") [options]

Options:
  --version=<tag>      talosctl version (e.g. v1.12.4)
  --install-dir=<dir>  installation directory override
  -h, --help           show this help
EOF_USAGE
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --version=*) TALOSCTL_VERSION="${1#*=}"; shift ;;
      --install-dir=*) INSTALL_DIR="${1#*=}"; shift ;;
      -h|--help) usage; exit 0 ;;
      *) usage; die "Unknown argument: $1" ;;
    esac
  done
}

ensure_bashrc_sources_init_dir() {
  local marker_begin="# >>> controller bashrc.d >>>"

  touch "${BASHRC_FILE}"
  if grep -Eq 'bashrc\.d' "${BASHRC_FILE}"; then
    return 0
  fi
  if grep -Fq "${marker_begin}" "${BASHRC_FILE}"; then
    return 0
  fi

  cat >>"${BASHRC_FILE}" <<'EOF_BASHRC'
# >>> controller bashrc.d >>>
if [[ -d "${HOME}/.bashrc.d" ]]; then
  for _controller_rc in "${HOME}"/.bashrc.d/*.sh; do
    [[ -f "${_controller_rc}" ]] || continue
    # shellcheck disable=SC1090
    source "${_controller_rc}"
  done
  unset _controller_rc
fi
# <<< controller bashrc.d <<<
EOF_BASHRC
}

configure_talosctl_completion() {
  mkdir -p "${SHELL_INIT_DIR}"
  cat >"${TALOSCTL_SHELL_FILE}" <<'EOF_TALOSCTL_RC'
# talosctl completion (generated by install-talosctl.sh)
if command -v talosctl >/dev/null 2>&1; then
  source <(talosctl completion bash)
fi
EOF_TALOSCTL_RC
  chmod 0644 "${TALOSCTL_SHELL_FILE}"
  ensure_bashrc_sources_init_dir
}

main() {
  local -a install_cmd=("${REPO_ROOT}/overlays/base/scripts/talos/install.sh" "--env=lab")

  parse_args "$@"

  if [[ -n "${TALOSCTL_VERSION}" ]]; then
    install_cmd+=("--version=${TALOSCTL_VERSION}")
  fi
  if [[ -n "${INSTALL_DIR}" ]]; then
    install_cmd+=("--install-dir=${INSTALL_DIR}")
  fi

  "${install_cmd[@]}"
  configure_talosctl_completion
  log_info "talosctl completion configured for new shells."
  log_info "Run: source ~/.bashrc"
}

main "$@"
