#!/usr/bin/env bash
# Variáveis PKR_VAR (referenciando variáveis originais)

# Packer Logging
echo -e '\n> Setting the Packer Logging...'
log_dir="/tmp/packer"
mkdir -p "${log_dir}"
export PACKER_LOG=1
export PACKER_LOG_PATH="${log_dir}/packer.log"
# export PACKER_HOST=192.168.0.1

export PKR_VAR_common_data_source="${common_data_source}"
export PKR_VAR_common_http_ip="${common_http_ip}"
export PKR_VAR_common_http_port_min="${common_http_port_min}"
export PKR_VAR_common_http_port_max="${common_http_port_max}"
export PKR_VAR_common_ip_wait_timeout="${common_ip_wait_timeout}"
export PKR_VAR_common_ip_settle_timeout="${common_ip_settle_timeout}"
export PKR_VAR_common_shutdown_timeout="${common_shutdown_timeout}"
export PKR_VAR_vsphere_endpoint="${vsphere_endpoint}"
export PKR_VAR_vsphere_username="${vsphere_username}"
export PKR_VAR_vsphere_password="${vsphere_password}"
export PKR_VAR_vsphere_insecure_connection="${vsphere_insecure_connection}"
export PKR_VAR_vsphere_datacenter="${vsphere_datacenter}"
export PKR_VAR_vsphere_cluster="${vsphere_cluster}"
export PKR_VAR_vsphere_host="${vsphere_host}"
export PKR_VAR_vsphere_datastore="${vsphere_datastore}"
export PKR_VAR_vsphere_network="${vsphere_network}"
export PKR_VAR_vsphere_folder="${vsphere_folder}"
export PKR_VAR_vsphere_resource_pool="${vsphere_resource_pool}"
export PKR_VAR_vsphere_set_host_for_datastore_uploads="${vsphere_set_host_for_datastore_uploads}"
export PKR_VAR_vsphere_api_timeout="${vsphere_api_timeout}"
export PKR_VAR_ansible_username="${ansible_username}"
export PKR_VAR_ansible_key="${ansible_key}"
export PKR_VAR_gh_username="${gh_username}"
export PKR_VAR_gh_token="${gh_token}"
export PKR_VAR_build_username="${build_username}"
export PKR_VAR_build_password="${build_password}"
export PKR_VAR_build_password_encrypted="${build_password_encrypted}"
export PKR_VAR_build_key="${build_key}"
export PKR_VAR_rhsm_username="${rhsm_username}"
export PKR_VAR_rhsm_password="${rhsm_password}"
export PKR_VAR_common_iso_datastore="${common_iso_datastore}"
export PKR_VAR_common_iso_content_library="${common_iso_content_library}"
export PKR_VAR_common_content_library_name="${common_content_library_name}"
export PKR_VAR_common_iso_content_library_enabled="${common_iso_content_library_enabled}"
export PKR_VAR_common_vm_version="${common_vm_version}"
export PKR_VAR_common_tools_upgrade_policy="${common_tools_upgrade_policy}"
export PKR_VAR_common_remove_cdrom="${common_remove_cdrom}"
export PKR_VAR_common_template_conversion="${common_template_conversion}"
export PKR_VAR_common_content_library="${common_content_library}"
export PKR_VAR_common_content_library_enabled="${common_content_library_enabled}"
export PKR_VAR_common_content_library_ovf="${common_content_library_ovf}"
export PKR_VAR_common_content_library_destroy="${common_content_library_destroy}"
export PKR_VAR_common_content_library_skip_export="${common_content_library_skip_export}"
export PKR_VAR_common_ovf_export_enabled="${common_ovf_export_enabled}"
export PKR_VAR_common_ovf_export_overwrite="${common_ovf_export_overwrite}"
export PKR_VAR_common_ovf_export_image_files="${common_ovf_export_image_files}"
export PKR_VAR_use_socks_proxy="${use_socks_proxy}"
export PKR_VAR_communicator_proxy_host="${communicator_proxy_host}"
export PKR_VAR_communicator_proxy_port="${communicator_proxy_port}"
export PKR_VAR_communicator_proxy_username="${communicator_proxy_username}"
export PKR_VAR_communicator_proxy_password="${communicator_proxy_password}"
export PKR_VAR_common_hcp_packer_registry_enabled="${common_hcp_packer_registry_enabled}"
