#!/usr/bin/env bash
# @file vars.sh
# @description Canonical default variables for the packer module.

# vSphere connection and inventory
export VSPHERE_ENDPOINT="${VSPHERE_ENDPOINT:-}"
export VSPHERE_USERNAME="${VSPHERE_USERNAME:-}"
export VSPHERE_PASSWORD="${VSPHERE_PASSWORD:-}"
export VSPHERE_INSECURE_CONNECTION="${VSPHERE_INSECURE_CONNECTION:-true}"
export VSPHERE_DATACENTER="${VSPHERE_DATACENTER:-}"
export VSPHERE_CLUSTER="${VSPHERE_CLUSTER:-}"
export VSPHERE_HOST="${VSPHERE_HOST:-}"
export VSPHERE_DATASTORE="${VSPHERE_DATASTORE:-}"
export VSPHERE_NETWORK="${VSPHERE_NETWORK:-}"
export VSPHERE_FOLDER="${VSPHERE_FOLDER:-}"
export VSPHERE_RESOURCE_POOL="${VSPHERE_RESOURCE_POOL:-}"
export VSPHERE_SET_HOST_FOR_DATASTORE_UPLOADS="${VSPHERE_SET_HOST_FOR_DATASTORE_UPLOADS:-false}"

# Build account
export BUILD_USERNAME="${BUILD_USERNAME:-}"
export BUILD_PASSWORD="${BUILD_PASSWORD:-}"
export BUILD_PASSWORD_ENCRYPTED="${BUILD_PASSWORD_ENCRYPTED:-}"
export BUILD_KEY="${BUILD_KEY:-}"
export ANSIBLE_USERNAME="${ANSIBLE_USERNAME:-}"
export ANSIBLE_KEY="${ANSIBLE_KEY:-}"

# Common packer settings
export COMMON_ISO_DATASTORE="${COMMON_ISO_DATASTORE:-}"
export COMMON_ISO_CONTENT_LIBRARY="${COMMON_ISO_CONTENT_LIBRARY:-}"
export COMMON_ISO_CONTENT_LIBRARY_ENABLED="${COMMON_ISO_CONTENT_LIBRARY_ENABLED:-false}"
export COMMON_VM_VERSION="${COMMON_VM_VERSION:-19}"
export COMMON_TOOLS_UPGRADE_POLICY="${COMMON_TOOLS_UPGRADE_POLICY:-true}"
export COMMON_REMOVE_CDROM="${COMMON_REMOVE_CDROM:-true}"
export COMMON_TEMPLATE_CONVERSION="${COMMON_TEMPLATE_CONVERSION:-false}"
export COMMON_CONTENT_LIBRARY="${COMMON_CONTENT_LIBRARY:-}"
export COMMON_CONTENT_LIBRARY_ENABLED="${COMMON_CONTENT_LIBRARY_ENABLED:-false}"
export COMMON_CONTENT_LIBRARY_OVF="${COMMON_CONTENT_LIBRARY_OVF:-true}"
export COMMON_CONTENT_LIBRARY_DESTROY="${COMMON_CONTENT_LIBRARY_DESTROY:-true}"
export COMMON_CONTENT_LIBRARY_SKIP_EXPORT="${COMMON_CONTENT_LIBRARY_SKIP_EXPORT:-false}"
export COMMON_OVF_EXPORT_ENABLED="${COMMON_OVF_EXPORT_ENABLED:-false}"
export COMMON_OVF_EXPORT_OVERWRITE="${COMMON_OVF_EXPORT_OVERWRITE:-true}"
export COMMON_OVF_EXPORT_IMAGE_FILES="${COMMON_OVF_EXPORT_IMAGE_FILES:-true}"
export COMMON_DATA_SOURCE="${COMMON_DATA_SOURCE:-disk}"
export COMMON_HTTP_IP="${COMMON_HTTP_IP:-}"
export COMMON_HTTP_PORT_MIN="${COMMON_HTTP_PORT_MIN:-8000}"
export COMMON_HTTP_PORT_MAX="${COMMON_HTTP_PORT_MAX:-8099}"
export COMMON_IP_WAIT_TIMEOUT="${COMMON_IP_WAIT_TIMEOUT:-20m}"
export COMMON_IP_SETTLE_TIMEOUT="${COMMON_IP_SETTLE_TIMEOUT:-5s}"
export COMMON_SHUTDOWN_TIMEOUT="${COMMON_SHUTDOWN_TIMEOUT:-15m}"
export COMMON_HCP_PACKER_REGISTRY_ENABLED="${COMMON_HCP_PACKER_REGISTRY_ENABLED:-false}"

# Optional proxy settings
export COMMUNICATOR_PROXY_HOST="${COMMUNICATOR_PROXY_HOST:-}"
export COMMUNICATOR_PROXY_PORT="${COMMUNICATOR_PROXY_PORT:-}"
export COMMUNICATOR_PROXY_USERNAME="${COMMUNICATOR_PROXY_USERNAME:-}"
export COMMUNICATOR_PROXY_PASSWORD="${COMMUNICATOR_PROXY_PASSWORD:-}"

# Optional packer logging
export PACKER_ENABLE_LOG="${PACKER_ENABLE_LOG:-false}"
export PACKER_LOG_PATH="${PACKER_LOG_PATH:-/tmp/packer/packer.log}"
