---
- name: Install keepalived package
  become: true
  ansible.builtin.package:
    name: keepalived
    state: present
    update_cache: true

- name: Start Keepalived Systemd Service
  become: true
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
    daemon_reload: true