---
- name: Ensure HAProxy cert directory exists
  become: true
  ansible.builtin.file:
    path: /etc/haproxy/certs
    state: directory
    owner: root
    group: "{{ haproxy_group }}"
    mode: "0750"

- name: Create HAProxy configuration file
  become: true
  ansible.builtin.template:
    src: "{{ haproxy_config_template }}"
    dest: "{{ haproxy_conf_file_path }}"
    owner: root
    group: "{{ haproxy_group }}"
    mode: "0640"
    validate: "{{ haproxy_executable_path }} -c -f %s"
  notify: Reload HAProxy
