#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

# shellcheck disable=SC1091
source "${REPO_ROOT}/overlays/base/scripts/functions.sh"

ACTION=""
LEGACY_ENV_NAME="lab"
VARS_FILE=""
LOCAL_VARS_FILE=""
PROJECT_DIR=""
CLUSTER_NAME=""
GENERATED_DIR=""
WORKER_COUNT=""
ADDON_NAME=""
ADDONS_LIST=""
DRY_RUN="false"

usage() {
  cat <<EOF_USAGE
Usage: $(basename "$0") <action> [options]

Actions:
  create-project  Create a new cluster project scaffold in --project-dir
  generate        Generate Talos configs and rendered patches
  provision       Provision Talos VMs (create)
  apply-config    Apply machine configuration to nodes
  bootstrap       Bootstrap Talos control plane
  apply-cluster-config  Apply mandatory post-bootstrap baseline (for example cilium, longhorn)
  install-addons  Install one addon (via Helm phase wrapper)
  sync-access     Sync local kubectl and talosctl access

Options:
  --vars-file=<path>              Explicit vars file (env-agnostic mode)
  --bootstrap-vars-file=<path>    Alias of --vars-file
  --local-vars-file=<path>        Optional local overrides file
  --project-dir=<path>            Cluster project dir (loads vars.sh and vars.local.sh from there)
  --cluster-name=<name>           Cluster name override
  --generated-dir=<path>          Generated output dir override
  --worker-count=<n>              Worker count override (provision only)
  --addons=<list>                 Addon list for apply-cluster-config (CSV/JSON-like)
  --addon=<name>                  Addon name (install-addons only)
  -n, --dry-run                   Print actions without executing
  -h, --help                      Show this help

Examples:
  $(basename "$0") create-project --project-dir=overlays/lab/talos/talos-dev
  $(basename "$0") generate --project-dir=overlays/lab/talos/talos-dev
  $(basename "$0") provision --project-dir=overlays/lab/talos/talos-dev
  $(basename "$0") apply-config --project-dir=overlays/lab/talos/talos-dev
  $(basename "$0") bootstrap
  $(basename "$0") apply-cluster-config --addons='[\"cilium\",\"longhorn\"]'
  $(basename "$0") install-addons --addon=cilium
  $(basename "$0") sync-access
EOF_USAGE
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      create-project|generate|provision|apply-config|bootstrap|apply-cluster-config|install-addons|sync-access)
        [[ -z "${ACTION}" ]] || die "Action already set: ${ACTION}"
        ACTION="$1"
        shift
        ;;
      --vars-file=*) VARS_FILE="${1#*=}"; shift ;;
      --bootstrap-vars-file=*) VARS_FILE="${1#*=}"; shift ;;
      --local-vars-file=*) LOCAL_VARS_FILE="${1#*=}"; shift ;;
      --project-dir=*) PROJECT_DIR="${1#*=}"; shift ;;
      --cluster-name=*) CLUSTER_NAME="${1#*=}"; shift ;;
      --generated-dir=*) GENERATED_DIR="${1#*=}"; shift ;;
      --worker-count=*) WORKER_COUNT="${1#*=}"; shift ;;
      --addons=*) ADDONS_LIST="${1#*=}"; shift ;;
      --addon=*) ADDON_NAME="${1#*=}"; shift ;;
      -n|--dry-run) DRY_RUN="true"; shift ;;
      -h|--help) usage; exit 0 ;;
      --env=*|--env)
        die "--env was removed. Use --project-dir or --vars-file."
        ;;
      *) usage; die "Unknown argument: $1" ;;
    esac
  done

  [[ -n "${ACTION}" ]] || { usage; die "Action is required."; }
}

run_or_echo() {
  if [[ "${DRY_RUN}" == "true" ]]; then
    log_info "[DRY-RUN] $*"
    return 0
  fi
  "$@"
}

create_project_scaffold() {
  local project_dir="$1"
  local cluster_name="$2"
  local base_vars_path="${REPO_ROOT}/overlays/base/scripts/vars.sh"
  local project_abs=""

  if [[ "${project_dir}" = /* ]]; then
    project_abs="${project_dir}"
  else
    project_abs="${REPO_ROOT}/${project_dir}"
  fi

  if [[ "${DRY_RUN}" == "true" ]]; then
    log_info "[DRY-RUN] create project scaffold at ${project_abs}"
    return 0
  fi

  mkdir -p "${project_abs}/patches" "${project_abs}/generated" "${project_abs}/helm"

  if [[ ! -f "${project_abs}/vars.sh" ]]; then
    cat > "${project_abs}/vars.sh" <<EOF_VARS
#!/usr/bin/env bash
set -euo pipefail

# Generated by cluster.sh create-project
BASE_VARS="${base_vars_path}"

if [[ ! -f "\${BASE_VARS}" ]]; then
  echo "[ERROR] Missing base vars file: \${BASE_VARS}" >&2
  return 1 2>/dev/null || exit 1
fi

# shellcheck source=/dev/null
source "\${BASE_VARS}"

export TALOS_CLUSTER_NAME="${cluster_name}"

# Fill these values for your environment:
export TALOS_CLUSTER_ENDPOINT="https://<vip>:6443"
export TALOS_CONTROL_PLANE_IPS='["192.168.0.61","192.168.0.62","192.168.0.63"]'
export TALOS_WORKER_IPS='["192.168.0.71","192.168.0.72","192.168.0.73"]'
export TALOS_GATEWAY="192.168.0.2"
export TALOS_NETMASK_PREFIX="24"
export TALOS_NAMESERVERS='["1.1.1.1","8.8.8.8"]'
export TALOS_DISABLE_DEFAULT_CNI="true"
export TALOS_CLUSTER_BASELINE_ADDONS='["cilium"]'

# Generated artifacts and machine configs
export TALOS_CONTROL_PLANE_CONFIG_PATH="${project_abs}/generated/controlplane.yaml"
export TALOS_WORKER_CONFIG_PATH="${project_abs}/generated/worker.yaml"
EOF_VARS
    chmod +x "${project_abs}/vars.sh"
  fi

  if [[ ! -f "${project_abs}/vars.local.example.sh" ]]; then
    cat > "${project_abs}/vars.local.example.sh" <<'EOF_LOCAL'
#!/usr/bin/env bash
# Copy to vars.local.sh and customize sensitive values.

export VSPHERE_ENDPOINT="192.168.0.233"
export VSPHERE_USERNAME="root"
export VSPHERE_PASSWORD="CHANGE_ME"
EOF_LOCAL
  fi

  if [[ ! -f "${project_abs}/.gitignore" ]]; then
    cat > "${project_abs}/.gitignore" <<'EOF_IGNORE'
vars.local.sh
generated/*
!generated/.gitkeep
EOF_IGNORE
  fi

  if [[ ! -f "${project_abs}/generated/.gitkeep" ]]; then
    : > "${project_abs}/generated/.gitkeep"
  fi

  if [[ ! -f "${project_abs}/cluster-spec.yaml" ]]; then
    cat > "${project_abs}/cluster-spec.yaml" <<EOF_SPEC
apiVersion: platform.labs/v1alpha1
kind: TalosClusterSpec
metadata:
  name: ${cluster_name}
spec:
  sourceOfTruth:
    varsFile: ${project_abs}/vars.sh
    localVarsFile: ${project_abs}/vars.local.sh
  workflow:
    generate: "cluster.sh generate --project-dir=${project_abs}"
    provision: "cluster.sh provision --project-dir=${project_abs}"
    applyConfig: "cluster.sh apply-config --project-dir=${project_abs}"
    bootstrap: "cluster.sh bootstrap --project-dir=${project_abs}"
    syncAccess: "cluster.sh sync-access --project-dir=${project_abs}"
    baseline: "cluster.sh apply-cluster-config --project-dir=${project_abs}"
EOF_SPEC
  fi

  if [[ ! -f "${project_abs}/README.md" ]]; then
    cat > "${project_abs}/README.md" <<EOF_README
# ${cluster_name}

This project was generated by:

\`\`\`bash
cluster.sh create-project --project-dir=${project_abs}
\`\`\`

## Quick Flow

1. Fill values in \`vars.sh\`.
2. Optionally create \`vars.local.sh\` from \`vars.local.example.sh\`.
3. Execute:

\`\`\`bash
cluster.sh generate --project-dir=${project_abs}
cluster.sh provision --project-dir=${project_abs}
cluster.sh apply-config --project-dir=${project_abs}
cluster.sh bootstrap --project-dir=${project_abs}
cluster.sh sync-access --project-dir=${project_abs}
cluster.sh apply-cluster-config --project-dir=${project_abs}
\`\`\`
EOF_README
  fi

  log_info "Project scaffold created: ${project_abs}"
}

main() {
  local -a cmd=()
  local project_vars_file=""
  local project_local_vars_file=""
  local project_abs=""
  local project_name=""

  parse_args "$@"

  if [[ -n "${PROJECT_DIR}" ]]; then
    if [[ "${PROJECT_DIR}" = /* ]]; then
      project_abs="${PROJECT_DIR}"
    else
      project_abs="${REPO_ROOT}/${PROJECT_DIR}"
    fi

    project_vars_file="${project_abs}/vars.sh"
    project_local_vars_file="${project_abs}/vars.local.sh"
    [[ -z "${VARS_FILE}" ]] && VARS_FILE="${project_vars_file}"
    [[ -z "${LOCAL_VARS_FILE}" ]] && LOCAL_VARS_FILE="${project_local_vars_file}"
    [[ -z "${CLUSTER_NAME}" ]] && CLUSTER_NAME="$(basename "${project_abs}")"
  fi

  if [[ "${ACTION}" != "create-project" && -z "${VARS_FILE}" ]]; then
    die "Missing vars source. Use --project-dir=<path> or --vars-file=<path>."
  fi

  if [[ -n "${VARS_FILE}" ]]; then
    export OVERLAY_VARS_FILE="${VARS_FILE}"
  fi
  if [[ -n "${LOCAL_VARS_FILE}" ]]; then
    export OVERLAY_LOCAL_VARS_FILE="${LOCAL_VARS_FILE}"
  fi

  case "${ACTION}" in
    create-project)
      [[ -n "${PROJECT_DIR}" ]] || die "--project-dir is required for create-project."
      project_name="${CLUSTER_NAME:-$(basename "${project_abs}")}"
      create_project_scaffold "${PROJECT_DIR}" "${project_name}"
      return 0
      ;;
    generate)
      cmd=("${SCRIPT_DIR}/cluster-bootstrap.sh" "--env=${LEGACY_ENV_NAME}" "--mode=generate")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ -n "${GENERATED_DIR}" ]] && cmd+=("--generated-dir=${GENERATED_DIR}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
    provision)
      cmd=("${SCRIPT_DIR}/provision-cluster.sh" "--env=${LEGACY_ENV_NAME}")
      [[ -n "${WORKER_COUNT}" ]] && cmd+=("--worker-count=${WORKER_COUNT}")
      cmd+=("create")
      ;;
    apply-config)
      cmd=("${SCRIPT_DIR}/cluster-bootstrap.sh" "--env=${LEGACY_ENV_NAME}" "--mode=apply")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ -n "${GENERATED_DIR}" ]] && cmd+=("--generated-dir=${GENERATED_DIR}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
    bootstrap)
      cmd=("${SCRIPT_DIR}/cluster-bootstrap.sh" "--env=${LEGACY_ENV_NAME}" "--mode=bootstrap")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ -n "${GENERATED_DIR}" ]] && cmd+=("--generated-dir=${GENERATED_DIR}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
    apply-cluster-config)
      cmd=("${SCRIPT_DIR}/apply-cluster-config.sh" "--env=${LEGACY_ENV_NAME}")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ -n "${ADDONS_LIST}" ]] && cmd+=("--addons=${ADDONS_LIST}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
    install-addons)
      [[ -n "${ADDON_NAME}" ]] || die "--addon is required for install-addons."
      cmd=("${SCRIPT_DIR}/phase-network-bringup.sh" "--env=${LEGACY_ENV_NAME}" "--addon=${ADDON_NAME}")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
    sync-access)
      cmd=("${SCRIPT_DIR}/sync-kubectl.sh" "--env=${LEGACY_ENV_NAME}")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      run_or_echo "${cmd[@]}"

      cmd=("${SCRIPT_DIR}/sync-talosctl.sh" "--env=${LEGACY_ENV_NAME}")
      [[ -n "${CLUSTER_NAME}" ]] && cmd+=("--cluster-name=${CLUSTER_NAME}")
      [[ "${DRY_RUN}" == "true" ]] && cmd+=("--dry-run")
      ;;
  esac

  run_or_echo "${cmd[@]}"
}

main "$@"
