#!/usr/bin/env bash
# @file vars.sh
# @description Defaults for DNS VM provisioning and dnsmasq configuration.

# GOVC provisioning defaults for DNS VM
export DNS_VM_COUNT="${DNS_VM_COUNT:-1}"
export DNS_VM_NAME_PREFIX="${DNS_VM_NAME_PREFIX:-talos-dns}"
export DNS_VM_START_INDEX="${DNS_VM_START_INDEX:-1}"
export DNS_VM_TEMPLATE_NAME="${DNS_VM_TEMPLATE_NAME:-}"
export DNS_VM_OVA_PATH="${DNS_VM_OVA_PATH:-}"
export DNS_VM_OVF_PATH="${DNS_VM_OVF_PATH:-}"
export DNS_VM_CPUS="${DNS_VM_CPUS:-1}"
export DNS_VM_MEMORY_MB="${DNS_VM_MEMORY_MB:-1024}"
export DNS_VM_DISK_GB="${DNS_VM_DISK_GB:-20}"
export DNS_VM_STATIC_IP="${DNS_VM_STATIC_IP:-}"
export DNS_VM_GATEWAY="${DNS_VM_GATEWAY:-}"
export DNS_VM_NETMASK_PREFIX="${DNS_VM_NETMASK_PREFIX:-24}"
export DNS_VM_STATIC_INTERFACE="${DNS_VM_STATIC_INTERFACE:-ens160}"
export DNS_VM_BOOTSTRAP_NAMESERVERS="${DNS_VM_BOOTSTRAP_NAMESERVERS:-1.1.1.1,8.8.8.8}"
export DNS_VM_GUEST_USERNAME="${DNS_VM_GUEST_USERNAME:-}"
export DNS_VM_GUEST_PASSWORD="${DNS_VM_GUEST_PASSWORD:-}"
export DNS_VM_GUEST_STATIC="${DNS_VM_GUEST_STATIC:-auto}"

# In-guest DNS service defaults
export DNS_PACKAGE_NAME="${DNS_PACKAGE_NAME:-dnsmasq}"
export DNS_SERVICE_NAME="${DNS_SERVICE_NAME:-dnsmasq}"
export DNS_CONFIG_PATH="${DNS_CONFIG_PATH:-/etc/dnsmasq.d/talos-lab.conf}"
export DNS_LISTEN_ADDRESSES="${DNS_LISTEN_ADDRESSES:-127.0.0.1}"
export DNS_UPSTREAM_SERVERS="${DNS_UPSTREAM_SERVERS:-1.1.1.1,8.8.8.8}"
export DNS_DOMAIN="${DNS_DOMAIN:-lab.local}"
export DNS_A_RECORDS="${DNS_A_RECORDS:-}"
export DNS_CACHE_SIZE="${DNS_CACHE_SIZE:-1000}"
