#!/usr/bin/env bash
set -euo pipefail

# Generated by talos-toolchain cluster.sh create-project
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_REPO_ROOT="$(cd "${PROJECT_DIR}/../../../.." && pwd)"
WORKSPACE_ROOT="$(dirname "${LAB_REPO_ROOT}")"

export TALOS_CLUSTER_NAME="talos-smoke"
export TALOS_CLUSTER_ENDPOINT="https://192.168.0.30:6443"

# Network defaults
export TALOS_GATEWAY="192.168.0.2"
export TALOS_NETMASK_PREFIX="24"
export TALOS_NODE_INTERFACE="eth0"
export TALOS_NAMESERVERS='["1.1.1.1","8.8.8.8"]'

# Topology defaults
export TALOS_CONTROL_PLANE_COUNT="3"
export TALOS_WORKER_COUNT="3"
export TALOS_CONTROL_PLANE_IPS='["192.168.0.61","192.168.0.62","192.168.0.63"]'
export TALOS_WORKER_IPS='["192.168.0.71","192.168.0.72","192.168.0.73"]'
export TALOS_CONTROL_PLANE_NAME_PREFIX="${TALOS_CLUSTER_NAME}-cp"
export TALOS_WORKER_NAME_PREFIX="${TALOS_CLUSTER_NAME}-worker"

# Images (refresh-schematics will set installer image IDs)
export TALOS_OVA_PATH="https://factory.talos.dev/image/c5ecff40b8990cd2ff7d219fb380ac73c7ef52517b9835f1fc2c4ca31247c921/v1.12.4/vmware-amd64.ova"
export TALOS_CONTROL_PLANE_INSTALLER_IMAGE="factory.talos.dev/vmware-installer/e28b4c4617ada7a49259eea655871bc29afe503001727d8b991b79251ed86ea6:v1.12.4"
export TALOS_WORKER_INSTALLER_IMAGE="factory.talos.dev/vmware-installer/c5ecff40b8990cd2ff7d219fb380ac73c7ef52517b9835f1fc2c4ca31247c921:v1.12.4"

# Generated machine config paths
export TALOS_CONTROL_PLANE_CONFIG_PATH="${PROJECT_DIR}/generated/controlplane.yaml"
export TALOS_WORKER_CONFIG_PATH="${PROJECT_DIR}/generated/worker.yaml"

# Day-1 action commands (must be set by your environment integration)
export TALOS_DAY1_GENERATE_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/cluster-bootstrap.sh --env=lab --mode=generate"
export TALOS_DAY1_PROVISION_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/provision-cluster.sh --env=lab create"
export TALOS_DAY1_PREPARE_BOOTSTRAP_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/cluster-bootstrap.sh --env=lab --mode=apply --apply-stage=pre"
export TALOS_DAY1_APPLY_CONFIG_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/cluster-bootstrap.sh --env=lab --mode=apply"
export TALOS_DAY1_BOOTSTRAP_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/cluster-bootstrap.sh --env=lab --mode=bootstrap"
export TALOS_DAY1_SYNC_ACCESS_CMD="${LAB_REPO_ROOT}/overlays/base/scripts/talos/sync-kubectl.sh --env=lab && ${LAB_REPO_ROOT}/overlays/base/scripts/talos/sync-talosctl.sh --env=lab"

# Day-1 baseline addons
export TALOS_CLUSTER_BASELINE_ADDONS='["cilium"]'
export TALOS_DAY1_REQUIRE_CILIUM="true"
export TALOS_DAY1_MANIFEST_ROOT_DIR="${WORKSPACE_ROOT}/talos-vsphere-gitops/environments/lab"
export TALOS_DAY1_KUBE_CONTEXT="admin@${TALOS_CLUSTER_NAME}"

export OVERLAY_VARS_FILE="${PROJECT_DIR}/vars.sh"

export OVERLAY_LOCAL_VARS_FILE="${PROJECT_DIR}/vars.local.sh"

export VSPHERE_ENDPOINT="192.168.0.233"

export VSPHERE_USERNAME="root"

export VSPHERE_PASSWORD="CHANGE_ME"

export VSPHERE_INSECURE_CONNECTION="true"

export VSPHERE_DATASTORE="DATASTORE_02"

export VSPHERE_NETWORK="VM Network"

export VSPHERE_FOLDER=""

export VSPHERE_RESOURCE_POOL=""

export SSH_USER="vagrant"

export HAPROXY_SSH_USER="vagrant"

export HAPROXY_NODE_1_NAME="talos-lb-1"

export HAPROXY_NODE_1_IP="192.168.0.31"

export HAPROXY_NODE_2_NAME="talos-lb-2"

export HAPROXY_NODE_2_IP="192.168.0.32"
