apiVersion: platform.labs/v1alpha1
kind: TalosClusterSpec
metadata:
  name: talos-dev
spec:
  sourceOfTruth:
    varsFile: /home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev/vars.sh
    localVarsFile: /home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev/vars.local.sh
  workflow:
    generate: "cluster.sh generate --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    provision: "cluster.sh provision --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    prepareBootstrap: "cluster.sh prepare-bootstrap --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    applyConfig: "cluster.sh apply-config --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    bootstrap: "cluster.sh bootstrap --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    syncAccess: "cluster.sh sync-access --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
    baseline: "cluster.sh apply-cluster-config --project-dir=/home/vagrant/talos-vsphere-lab/overlays/lab/talos/talos-dev"
