#!/usr/bin/env bash
set -euo pipefail

# Generated by cluster.sh create-project
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_REPO_ROOT="$(cd "${PROJECT_DIR}/../../../.." && pwd)"
WORKSPACE_ROOT="$(dirname "${LAB_REPO_ROOT}")"
BASE_VARS="${LAB_REPO_ROOT}/overlays/base/scripts/vars.sh"

if [[ ! -f "${BASE_VARS}" ]]; then
  echo "[ERROR] Missing base vars file: ${BASE_VARS}" >&2
  return 1 2>/dev/null || exit 1
fi

# shellcheck source=/dev/null
source "${BASE_VARS}"

export TALOS_CLUSTER_NAME="talos-dev"

# vSphere target (required for provision)
export VSPHERE_ENDPOINT="192.168.0.233"
export VSPHERE_USERNAME="root"
export VSPHERE_PASSWORD="CHANGE_ME"
export VSPHERE_INSECURE_CONNECTION="true"
export VSPHERE_DATASTORE="DATASTORE_02"
export VSPHERE_NETWORK="VM Network"
export VSPHERE_FOLDER=""
export VSPHERE_RESOURCE_POOL=""

# SSH user defaults (controller -> helper VMs such as HAProxy/DNS)
export BUILD_USERNAME="vagrant"
export SSH_USER="vagrant"
export ANSIBLE_USER="${ANSIBLE_USER:-${SSH_USER}}"
export ANSIBLE_USERNAME="${ANSIBLE_USERNAME:-${SSH_USER}}"
export SSH_PORT="22"
export HAPROXY_SSH_USER="${HAPROXY_SSH_USER:-${SSH_USER}}"

# Talos access endpoint
export HAPROXY_VIP="192.168.0.30"
export HAPROXY_NODE_1_NAME="talos-lb-1"
export HAPROXY_NODE_1_IP="192.168.0.31"
export HAPROXY_NODE_2_NAME="talos-lb-2"
export HAPROXY_NODE_2_IP="192.168.0.32"
export TALOS_CLUSTER_ENDPOINT="https://${HAPROXY_VIP}:6443"

# Talos image source (choose one primary strategy)
export TALOS_OVA_PATH="https://factory.talos.dev/image/c5ecff40b8990cd2ff7d219fb380ac73c7ef52517b9835f1fc2c4ca31247c921/v1.12.4/vmware-amd64.ova"
export TALOS_ISO_DATASTORE_PATH="ISOs/talos-v1.12.4-uefi.iso"
# Optional local ISO used for automatic datastore upload in ISO mode
export TALOS_ISO_LOCAL_PATH=""

# Cluster topology
export TALOS_CONTROL_PLANE_COUNT="3"
export TALOS_WORKER_COUNT="3"
export TALOS_CONTROL_PLANE_IPS='["192.168.0.61","192.168.0.62","192.168.0.63"]'
export TALOS_WORKER_IPS='["192.168.0.71","192.168.0.72","192.168.0.73"]'
export TALOS_CONTROL_PLANE_NAME_PREFIX="${TALOS_CLUSTER_NAME}-cp"
export TALOS_WORKER_NAME_PREFIX="${TALOS_CLUSTER_NAME}-worker"

# Node resources
export TALOS_CONTROL_PLANE_CPU="2"
export TALOS_CONTROL_PLANE_MEMORY_MB="4096"
export TALOS_CONTROL_PLANE_DISK_GB="20"
export TALOS_CONTROL_PLANE_EXTRA_DISK_GB="40"
export TALOS_WORKER_CPU="2"
export TALOS_WORKER_MEMORY_MB="4096"
export TALOS_WORKER_DISK_GB="40"
export TALOS_WORKER_EXTRA_DISK_GB="40"

# Networking
export TALOS_GATEWAY="192.168.0.2"
export TALOS_NETMASK_PREFIX="24"
export TALOS_NODE_INTERFACE="eth0"
# Keep false when using external LB (HAProxy/keepalived VIP).
# Enable only if you intentionally run Talos CP interface VIP with a distinct IP.
export TALOS_CONTROL_PLANE_VIP_ENABLED="false"
export TALOS_CONTROL_PLANE_VIP="${HAPROXY_VIP}"
export TALOS_NAMESERVERS='["1.1.1.1","8.8.8.8"]'

# CNI baseline
export TALOS_DISABLE_DEFAULT_CNI="true"
export TALOS_CLUSTER_BASELINE_ADDONS='["cilium"]'
export TALOS_POST_BOOTSTRAP_HELM_AUTO_PREPARE="true"
export TALOS_POST_BOOTSTRAP_HELM_SOURCE_MODE="path"
export TALOS_POST_BOOTSTRAP_HELM_SOURCE_PATH="${WORKSPACE_ROOT}/talos-vsphere-gitops/environments/lab/helm"
export TALOS_POST_BOOTSTRAP_HELM_SOURCE_URL=""
export TALOS_POST_BOOTSTRAP_HELM_OVERWRITE="true"

# Generated artifacts and machine configs
export TALOS_CONTROL_PLANE_CONFIG_PATH="${PROJECT_DIR}/generated/controlplane.yaml"
export TALOS_WORKER_CONFIG_PATH="${PROJECT_DIR}/generated/worker.yaml"

export TALOS_CONTROL_PLANE_INSTALLER_IMAGE="factory.talos.dev/vmware-installer/e28b4c4617ada7a49259eea655871bc29afe503001727d8b991b79251ed86ea6:v1.12.4"

export TALOS_WORKER_INSTALLER_IMAGE="factory.talos.dev/vmware-installer/c5ecff40b8990cd2ff7d219fb380ac73c7ef52517b9835f1fc2c4ca31247c921:v1.12.4"
